name: "02 - Workflow Events"

on:
  pull_request: # Manual trigger from GitHub UI

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Event name:'${{ github.event_name }}'"
