name: 03 workflow runners

on:
  push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: echo "I am running on $RUNNER_OS"

  windows:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: echo "I am running on $RUNNER_OS"

#  macos:
#    runs-on: macos-latest
#    steps:
#     - name: Show OS
#       run: echo "Run for $RUNNER_OS"
