name: 10- Working with Matrices

on:
  workflow_dispatch

jobs:
  backwards-compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x, 18.x, 21.x]
        os:
          - ubuntu-latest
          - windows-latest

    name: ${{ matrix.os }}-Node${{ matrix.node-version }}

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: perform some tests
        run: |
         echo "Running tests on OS $matrix.os and $matrix.node-version
