name: 11 - 1 - Reusable Workflows - Reusable Definition

on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.build-status }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build
      id: build
      run: |
        echo "Building using directory ${{ inputs.target-directory }}"
        echo "::set-output name=build-status::success"

    - name: Deploy
      id: deploy
      run: |
        echo "Deploying build artifacts"
        echo "::set-output name=url::https://www.google.com"
